// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceFinder.Backend.Context;

namespace ServiceFinder.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceFinder.App.Model.ReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("EverUsed");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ObjectId");

                    b.Property<int>("OverAllReview");

                    b.Property<string>("ReviewTest");

                    b.Property<DateTime>("ReviewTime");

                    b.Property<bool>("ShowOptions");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("ServiceFinder.Main.Model.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 433, DateTimeKind.Local).AddTicks(7215),
                            IsActive = false,
                            Name = "Hospitality"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(2808),
                            IsActive = false,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(2814),
                            IsActive = false,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(2815),
                            IsActive = false,
                            Name = "Media"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(2816),
                            IsActive = false,
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("ServiceFinder.Main.Model.CityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(5696),
                            IsActive = false,
                            Name = "Kathmandu"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6160),
                            IsActive = false,
                            Name = "Pokhara"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6164),
                            IsActive = false,
                            Name = "Lalitpur"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6165),
                            IsActive = false,
                            Name = "Biratnagar"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6167),
                            IsActive = false,
                            Name = "Birjung"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6168),
                            IsActive = false,
                            Name = "Bharatpur"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6169),
                            IsActive = false,
                            Name = "Dharan"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6171),
                            IsActive = false,
                            Name = "Butwal"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6173),
                            IsActive = false,
                            Name = "Janakpur"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6175),
                            IsActive = false,
                            Name = "Dhangadhi"
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6177),
                            IsActive = false,
                            Name = "Bhaktapur"
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6178),
                            IsActive = false,
                            Name = "Nepalgunj"
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6178),
                            IsActive = false,
                            Name = "Hetauda"
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6179),
                            IsActive = false,
                            Name = "Itahari"
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6180),
                            IsActive = false,
                            Name = "Banepa"
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6181),
                            IsActive = false,
                            Name = "Dhulikhel"
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(6181),
                            IsActive = false,
                            Name = "Baglung"
                        });
                });

            modelBuilder.Entity("ServiceFinder.Main.Model.ObjectModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalEmail");

                    b.Property<string>("AdditionalPhoneNumber");

                    b.Property<int>("CategoryId");

                    b.Property<int>("CityId");

                    b.Property<string>("CompanyName");

                    b.Property<string>("CoverImageUrl");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<bool>("IsActive");

                    b.Property<string>("MapLink");

                    b.Property<string>("Name");

                    b.Property<string>("OriginalCoverImageName");

                    b.Property<string>("OriginalProfileImageName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("ProfileImageUrl");

                    b.Property<TimeSpan?>("ServiceCloseTime");

                    b.Property<TimeSpan?>("ServiceOpenTime");

                    b.Property<bool>("Status");

                    b.Property<string>("UserId");

                    b.Property<string>("WebLink");

                    b.HasKey("Id");

                    b.ToTable("objects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CityId = 1,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8304),
                            IsActive = false,
                            Name = "Hospitality Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CityId = 2,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8744),
                            IsActive = false,
                            Name = "Hospitality Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CityId = 3,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8750),
                            IsActive = false,
                            Name = "Hospitality Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CityId = 4,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8752),
                            IsActive = false,
                            Name = "Hospitality Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CityId = 5,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8753),
                            IsActive = false,
                            Name = "Hospitality Service 5",
                            Status = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CityId = 6,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8955),
                            IsActive = false,
                            Name = "Travel Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CityId = 7,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8957),
                            IsActive = false,
                            Name = "Travel Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CityId = 8,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8957),
                            IsActive = false,
                            Name = "Travel Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CityId = 9,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8958),
                            IsActive = false,
                            Name = "Travel Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CityId = 10,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(8959),
                            IsActive = false,
                            Name = "Travel Service 5",
                            Status = false
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CityId = 11,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9013),
                            IsActive = false,
                            Name = "Transportation Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CityId = 12,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9014),
                            IsActive = false,
                            Name = "Transportation Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CityId = 13,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9017),
                            IsActive = false,
                            Name = "Transportation Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CityId = 14,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9018),
                            IsActive = false,
                            Name = "Transportation Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CityId = 15,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9019),
                            IsActive = false,
                            Name = "Transportation Service 5",
                            Status = false
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CityId = 16,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9030),
                            IsActive = false,
                            Name = "Media Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CityId = 17,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9033),
                            IsActive = false,
                            Name = "Media Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CityId = 1,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9033),
                            IsActive = false,
                            Name = "Media Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CityId = 2,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9034),
                            IsActive = false,
                            Name = "Media Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CityId = 3,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9036),
                            IsActive = false,
                            Name = "Media Service 5",
                            Status = false
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CityId = 4,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9047),
                            IsActive = false,
                            Name = "Entertainment Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CityId = 5,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9050),
                            IsActive = false,
                            Name = "Entertainment Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CityId = 6,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9051),
                            IsActive = false,
                            Name = "Entertainment Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CityId = 7,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9052),
                            IsActive = false,
                            Name = "Entertainment Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CityId = 8,
                            CreatedOn = new DateTime(2019, 10, 22, 11, 9, 36, 434, DateTimeKind.Local).AddTicks(9053),
                            IsActive = false,
                            Name = "Entertainment Service 5",
                            Status = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
