// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAM.Framework.DataAccess.Contexts.AccountManagement;

namespace ServiceFinder.Framework.DataAccess.Migrations
{
    [DbContext(typeof(ServiceFinderDbContext))]
    partial class ServiceFinderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new { Id = "2b8d9187-3377-4dd8-ab3a-3b6b4302705d", ConcurrencyStamp = "54a13206-61f4-4f34-8931-a3c560347822", Name = "admin", NormalizedName = "ADMIN" },
                        new { Id = "4f1e6e2e-426b-434e-819f-dc19f227ab89", ConcurrencyStamp = "190b53e2-27b3-4d14-bd1f-784be98d5654", Name = "user", NormalizedName = "USER" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ServiceFinder.Framework.Model.Entity.UserDashboard.ServiceReviewEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<bool>("EverUsed");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OverAllReview");

                    b.Property<string>("ReviewTest");

                    b.Property<DateTime>("ReviewTime");

                    b.Property<int>("ServiceItemId");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.HasIndex("UserId");

                    b.ToTable("serviceReview");
                });

            modelBuilder.Entity("ServiceFinder.Framework.Model.Models.UserDashboard.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.Property<bool>("Status");

                    b.Property<string>("SystemDefinedImageName");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new { Id = 1, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 965, DateTimeKind.Local), Name = "Hospitality", Status = false },
                        new { Id = 2, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Travel", Status = false },
                        new { Id = 3, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Transportation", Status = false },
                        new { Id = 4, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Media", Status = false },
                        new { Id = 5, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Entertainment", Status = false }
                    );
                });

            modelBuilder.Entity("ServiceFinder.Framework.Model.Models.UserDashboard.ServiceItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CoverImageUrl");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("OriginalCoverImageName");

                    b.Property<string>("OriginalProfileImageName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("ProfileImageUrl");

                    b.Property<TimeSpan?>("ServiceCloseTime");

                    b.Property<TimeSpan?>("ServiceOpenTime");

                    b.Property<bool>("Status");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("serviceItems");

                    b.HasData(
                        new { Id = 1, CategoryId = 1, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Hospitality Service 1", Status = false },
                        new { Id = 2, CategoryId = 1, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Hospitality Service 2", Status = false },
                        new { Id = 3, CategoryId = 1, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Hospitality Service 3", Status = false },
                        new { Id = 4, CategoryId = 1, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Hospitality Service 4", Status = false },
                        new { Id = 5, CategoryId = 1, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Hospitality Service 5", Status = false },
                        new { Id = 6, CategoryId = 2, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Travel Service 1", Status = false },
                        new { Id = 7, CategoryId = 2, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Travel Service 2", Status = false },
                        new { Id = 8, CategoryId = 2, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Travel Service 3", Status = false },
                        new { Id = 9, CategoryId = 2, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Travel Service 4", Status = false },
                        new { Id = 10, CategoryId = 2, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Travel Service 5", Status = false },
                        new { Id = 11, CategoryId = 3, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Transportation Service 1", Status = false },
                        new { Id = 12, CategoryId = 3, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Transportation Service 2", Status = false },
                        new { Id = 13, CategoryId = 3, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Transportation Service 3", Status = false },
                        new { Id = 14, CategoryId = 3, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Transportation Service 4", Status = false },
                        new { Id = 15, CategoryId = 3, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Transportation Service 5", Status = false },
                        new { Id = 16, CategoryId = 4, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Media Service 1", Status = false },
                        new { Id = 17, CategoryId = 4, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Media Service 2", Status = false },
                        new { Id = 18, CategoryId = 4, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Media Service 3", Status = false },
                        new { Id = 19, CategoryId = 4, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Media Service 4", Status = false },
                        new { Id = 20, CategoryId = 4, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Media Service 5", Status = false },
                        new { Id = 21, CategoryId = 5, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Entertainment Service 1", Status = false },
                        new { Id = 22, CategoryId = 5, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Entertainment Service 2", Status = false },
                        new { Id = 23, CategoryId = 5, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Entertainment Service 3", Status = false },
                        new { Id = 24, CategoryId = 5, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Entertainment Service 4", Status = false },
                        new { Id = 25, CategoryId = 5, CreationDate = new DateTime(2019, 6, 5, 14, 31, 47, 966, DateTimeKind.Local), Name = "Entertainment Service 5", Status = false }
                    );
                });

            modelBuilder.Entity("ServiceFinder.Framework.Model.Models.UserDashboard.ServiceItemImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("ImageURL");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("OriginalImageName");

                    b.Property<int>("ServiceItemId");

                    b.Property<string>("SystemDefinedImageName");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceItemId");

                    b.ToTable("serviceItemImages");
                });

            modelBuilder.Entity("TAM.Framework.Model.Models.AccountManagement.ApplicationUserEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("Address");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("OriginalImageName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("Status");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TAM.Framework.Model.Models.AccountManagement.ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TAM.Framework.Model.Models.AccountManagement.ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TAM.Framework.Model.Models.AccountManagement.ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TAM.Framework.Model.Models.AccountManagement.ApplicationUserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ServiceFinder.Framework.Model.Entity.UserDashboard.ServiceReviewEntity", b =>
                {
                    b.HasOne("ServiceFinder.Framework.Model.Models.UserDashboard.ServiceItemEntity", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TAM.Framework.Model.Models.AccountManagement.ApplicationUserEntity", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ServiceFinder.Framework.Model.Models.UserDashboard.ServiceItemEntity", b =>
                {
                    b.HasOne("ServiceFinder.Framework.Model.Models.UserDashboard.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("TAM.Framework.Model.Models.AccountManagement.ApplicationUserEntity", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ServiceFinder.Framework.Model.Models.UserDashboard.ServiceItemImageEntity", b =>
                {
                    b.HasOne("ServiceFinder.Framework.Model.Models.UserDashboard.ServiceItemEntity", "ServiceItem")
                        .WithMany()
                        .HasForeignKey("ServiceItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
