// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Servicefinder.Core.DatabaseContext;

namespace Servicefinder.Core.Migrations
{
    [DbContext(typeof(CommonDbContext))]
    [Migration("20190926040337_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Servicefinder.Core.Model.AnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnswerText");

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("QuestionId");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.HasKey("Id");

                    b.ToTable("answer");
                });

            modelBuilder.Entity("Servicefinder.Core.Model.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<string>("Name");

                    b.Property<bool>("Status");

                    b.Property<string>("SystemDefinedImageName");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 287, DateTimeKind.Local).AddTicks(8428),
                            Name = "Hospitality",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(4029),
                            Name = "Travel",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(4035),
                            Name = "Transportation",
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(4036),
                            Name = "Media",
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(4037),
                            Name = "Entertainment",
                            Status = false
                        });
                });

            modelBuilder.Entity("Servicefinder.Core.Model.CityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Province");

                    b.Property<bool>("Status");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.HasKey("Id");

                    b.ToTable("city");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8137),
                            Name = "Kathmandu",
                            Province = "3",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8604),
                            Name = "Pokhara",
                            Province = "Gandaki",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8608),
                            Name = "Lalitpur",
                            Province = "3",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8610),
                            Name = "Biratnagar",
                            Province = "1",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8612),
                            Name = "Birjung",
                            Province = "2",
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8613),
                            Name = "Bharatpur",
                            Province = "3",
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8614),
                            Name = "Dharan",
                            Province = "1",
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8615),
                            Name = "Butwal",
                            Province = "5",
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8616),
                            Name = "Janakpur",
                            Province = "2",
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8617),
                            Name = "Dhangadhi",
                            Province = "Sudurpashchim",
                            Status = true
                        },
                        new
                        {
                            Id = 11,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8618),
                            Name = "Bhaktapur",
                            Province = "3",
                            Status = true
                        },
                        new
                        {
                            Id = 12,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8619),
                            Name = "Nepalgunj",
                            Province = "5",
                            Status = true
                        },
                        new
                        {
                            Id = 13,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8620),
                            Name = "Hetauda",
                            Province = "3",
                            Status = true
                        },
                        new
                        {
                            Id = 14,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8623),
                            Name = "Itahari",
                            Province = "1",
                            Status = true
                        },
                        new
                        {
                            Id = 15,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8624),
                            Name = "Banepa",
                            Province = "3",
                            Status = true
                        },
                        new
                        {
                            Id = 16,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8625),
                            Name = "Dhulikhel",
                            Province = "3",
                            Status = true
                        },
                        new
                        {
                            Id = 17,
                            CreatedOn = new DateTime(2019, 9, 26, 9, 48, 37, 288, DateTimeKind.Local).AddTicks(8626),
                            Name = "Baglung",
                            Province = "Gandaki",
                            Status = true
                        });
                });

            modelBuilder.Entity("Servicefinder.Core.Model.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<DateTime>("DateTime");

                    b.Property<string>("QuestionText");

                    b.Property<int>("ServiceItemId");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("question");
                });

            modelBuilder.Entity("Servicefinder.Core.Model.ServiceItemImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("ImageURL");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("OriginalImageName");

                    b.Property<int>("ServiceItemId");

                    b.Property<string>("SystemDefinedImageName");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.HasKey("Id");

                    b.ToTable("serviceItemImages");
                });

            modelBuilder.Entity("Servicefinder.Core.Model.ServiceItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId");

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<int?>("CityId");

                    b.Property<string>("CoverImageUrl");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("OriginalCoverImageName");

                    b.Property<string>("OriginalProfileImageName");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("ProfileImageUrl");

                    b.Property<TimeSpan?>("ServiceCloseTime");

                    b.Property<TimeSpan?>("ServiceOpenTime");

                    b.Property<bool>("Status");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("serviceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CityId = 1,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1104),
                            Name = "Hospitality Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CityId = 2,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1600),
                            Name = "Hospitality Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CityId = 3,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1606),
                            Name = "Hospitality Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CityId = 4,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1607),
                            Name = "Hospitality Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CityId = 5,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1609),
                            Name = "Hospitality Service 5",
                            Status = false
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CityId = 6,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1819),
                            Name = "Travel Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CityId = 7,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1821),
                            Name = "Travel Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CityId = 8,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1822),
                            Name = "Travel Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CityId = 9,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1823),
                            Name = "Travel Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CityId = 10,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1824),
                            Name = "Travel Service 5",
                            Status = false
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CityId = 11,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1841),
                            Name = "Transportation Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CityId = 12,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1843),
                            Name = "Transportation Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CityId = 13,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1844),
                            Name = "Transportation Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CityId = 14,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1845),
                            Name = "Transportation Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CityId = 15,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1846),
                            Name = "Transportation Service 5",
                            Status = false
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            CityId = 16,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1858),
                            Name = "Media Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CityId = 17,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1859),
                            Name = "Media Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            CityId = 1,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1860),
                            Name = "Media Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CityId = 2,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1920),
                            Name = "Media Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CityId = 3,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1923),
                            Name = "Media Service 5",
                            Status = false
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            CityId = 4,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1938),
                            Name = "Entertainment Service 1",
                            Status = false
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            CityId = 5,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1939),
                            Name = "Entertainment Service 2",
                            Status = false
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            CityId = 6,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1940),
                            Name = "Entertainment Service 3",
                            Status = false
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            CityId = 7,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1941),
                            Name = "Entertainment Service 4",
                            Status = false
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CityId = 8,
                            CreationDate = new DateTime(2019, 9, 26, 9, 48, 37, 289, DateTimeKind.Local).AddTicks(1942),
                            Name = "Entertainment Service 5",
                            Status = false
                        });
                });

            modelBuilder.Entity("Servicefinder.Core.Model.ServiceItemViewLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<int>("ServiceItemId");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserId");

                    b.Property<int>("ViewCount");

                    b.HasKey("Id");

                    b.ToTable("ServiceItemViewLogModel");
                });

            modelBuilder.Entity("Servicefinder.Core.Model.ServiceReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<bool>("EverUsed");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("OverAllReview");

                    b.Property<string>("ReviewTest");

                    b.Property<DateTime>("ReviewTime");

                    b.Property<int>("ServiceItemId");

                    b.Property<bool>("ShowOptions");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("serviceReview");
                });

            modelBuilder.Entity("Servicefinder.Core.Model.SubscriberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ChangeDate");

                    b.Property<string>("ChangedBy");

                    b.Property<string>("CreatedBy");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("CreationDate");

                    b.Property<string>("Email");

                    b.Property<string>("UserChangedId");

                    b.Property<string>("UserCreatedId");

                    b.HasKey("Id");

                    b.ToTable("subscriber");
                });
#pragma warning restore 612, 618
        }
    }
}
